export const crmKeys = {
  dashboard: () => ["crm-dashboard"] as const,
  profiles: () => ["crm-profiles"] as const,
  profileByCustomer: (sourceCustomerId: string) => ["crm-profile-by-customer", sourceCustomerId] as const,
  followUps: () => ["crm-follow-ups"] as const,
  relations: (customerId: string) => ["crm-relations", customerId] as const,
  relationsAll: () => ["crm-relations-all"] as const,
  customersForCrm: () => ["customers-for-crm"] as const,
  assignees: () => ["crm-assignees"] as const,
  customers: () => ["customers"] as const,
  customersList: () => ["customers-list"] as const,
  customerApplications: () => ["crm-customer-applications"] as const,
  regionManagers: () => ["crm-region-managers"] as const,
  representativeOps: () => ["crm-representative-ops"] as const,
  representativeOpsDetail: (repId: string) => ["crm-representative-ops", repId] as const,
  representativeReport: (repId: string, period = "week") => ["crm-representative-report", repId, period] as const,
  customerPool: () => ["crm-customer-pool"] as const,
  assignmentLogs: (profileId: string) => ["crm-assignment-logs", profileId] as const,
};
